name: Deploy Frontend to Azure

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust to match your app's Node version (e.g., 18 or 22)

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  # Ensure this matches your package.json scripts

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: trademinutes-app
          publish-profile: ${{ secrets.PUBLISH_PROFILE_FRONTEND }}
          package: ./build